### ISSUE TITLE
Tailwind Nested CSS Improperly Configured

### ISSUE THREAD

**Issue by Aaron-Vandersluys-Code** [Chameleon-company/Chameleon-Website#132]
Tailwind nested CSS has not been properly configured in the following components: 

/src/components/portfolio_card/portfolio_card-media.css
/src/pages/about/aboutUs-media.css

Steps to replicate - simply start the web application from the command terminal and you will receive the error warning within the front_end_project terminal. Does not effect ability to run the website but leaves us with un-configured code, which does not meet professional presentation practices.  

Required fixes - Configure Tailwind in the listed components for nested functionality. 

Refer to this documentation source for more information: https://tailwindcss.com/docs/using-with-preprocessors#nesting 

Error message as captured from terminal: 
![Nested CSS](https://github.com/Chameleon-company/Chameleon-Website/assets/87591425/1ef0f4f0-00bf-40b8-8da8-858794eca25f)

**Comment by KNSHQ** [comment]
This doesn't appear anymore.

**Comment by KNSHQ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Complete issue fixes listed on Github](https://trello.com/c/141H6a75/326-complete-issue-fixes-listed-on-github)
