### ISSUE TITLE
Signup Page Broken / Incomplete 

### ISSUE THREAD

**Issue by ghost** [Chameleon-company/Chameleon-Website#133]
The signup page (for creating new accounts on the Chameleon website) is completely broken, in terms of displaying assets and is missing functionality in code to allow new users to signup through existing Firebase implementation. Old logo and design language also present. 

Steps to replicate - none required, this is represented simply by the current state of component. 

Required fixes - Implement Tailwind CSS to ensure design is correctly displaying. Collaborate with design team on refreshing the design to be consistent with rest of the website. Update component code to integrate feature with our Google Firebase implementation.

Screenshot of how the page currently displays through web browser: 
<img width="1111" alt="Signup page broken" src="https://github.com/Chameleon-company/Chameleon-Website/assets/87591425/c283097f-2e07-478f-b9c8-753fc2335ba2">

**Comment by KNSHQ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Complete issue fixes listed on Github](https://trello.com/c/141H6a75/326-complete-issue-fixes-listed-on-github)
