### ISSUE TITLE
Resources Page Background Colour Not Filling Entire Display Area

### ISSUE THREAD

**Issue by ghost** [Chameleon-company/Chameleon-Website#134]
The green which is used as the background colour for several of our pages is not filling the entire display on larger screens in the resources page section. 

Steps to replicate - simply run the website on a larger display (32 inch tested on my end) end maximise the browser window. 

Required fixes - Update styling on resources page to ensure background colour fills entire screen area. 

Screenshot of issue: 
![Resources green not filling screen](https://github.com/Chameleon-company/Chameleon-Website/assets/87591425/7fce2806-cb7e-4fb0-87bc-0ceef47a900a)

**Comment by KNSHQ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Complete issue fixes listed on Github](https://trello.com/c/141H6a75/326-complete-issue-fixes-listed-on-github)
