### ISSUE TITLE
Large Headers, or Similar Styling Component Appearing on Some Pages 

### ISSUE THREAD

**Issue by ghost** [Chameleon-company/Chameleon-Website#138]
Some pages, such as news and pages within the resources section, appear to have excessively large headers on the page, which leads to unprofessional looking presentation standards. 

Steps to replicate - Run the website and navigate to the previously listed pages. 

Required fixes - Remove the unnecessary styling components causing this issue on effected pages. 

Screenshots of issue: 
![Large header 1](https://github.com/Chameleon-company/Chameleon-Website/assets/87591425/588b97d7-ce66-4008-b530-6049d6dd219b)
![Large header 2](https://github.com/Chameleon-company/Chameleon-Website/assets/87591425/4ad929e0-0943-4342-b04d-7a2c96b93877)

**Comment by KNSHQ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Complete issue fixes listed on Github](https://trello.com/c/141H6a75/326-complete-issue-fixes-listed-on-github)
